<div class="body_padded">
	<h1>Vulnerability: Command Execution</h1>
	<p>(Look in the vulnerabilities folder under: <b>ci</b>)</p>
	<h3>Activity</h3>
	<p>Enter: <pre>127.0.0.1</pre></p>
	<p>Now try this: <pre>127.0.0.1;ls -l /etc</pre></p>
	<div class="vulnerable_code_area">
		<h2>Ping for FREE</h2>
		<form name="ping" method="post">
			<label>Enter an IP address</label>
			<input type="text" name="ip" size="30">
			<br/><br/><input type="submit" value="submit" name="submit">
		</form>
		<?php echo $this->html?>
	</div>
	<h2>For more info:</h2>
	<ul>
		<li><a href="http://www.scribd.com/doc/2530476/Php-Endangers-Remote-Code-Execution" target="_blank">Php Endangers Remote Code Execution</a></li>
		<li><a href="http://www.ss64.com/bash/" target="_blank">ss64.com bash</a></li>
	</ul>
</div>
