<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Security Training Login</title>
    <!--This works fine on a dedicated vhost-->
    <link rel="stylesheet" type="text/css" href="<?= $this->url . 'css/login.css' ?>"/>
</head>
<body>
<div align="center">
    <p><img src="<?php echo 'images/logo.png' ?>" width="400px" height="auto"/></p>
    <form action="index.php" method="post">
        <fieldset>
            <label for="user">Username</label>
            <input type="text" class="loginInput" size="20" name="username"><br/>
            <label for="pass">Password</label>
            <input type="password" class="loginInput" AUTOCOMPLETE="off" size="20" name="password"><br/>
            <br />
            <p class="submit"><input type="submit" value="login" name="action"></p>
        </fieldset>
    </form>
    <br/>
    <?php echo $this->messagesHtml ?>
<br/>
<p><?= $this->company?></p>
</div>
</body>
</html>