<div class="body_padded">
	<h1>Welcome to Web Security Training </h1>
	<p>This is a horribly insecure web application, loaded with vulnerabilities. It is our class application, intended for developers to test their skills in a legal environment. Developers can then better understand pitfalls in web security.</p>
	<h2>DISCLAIMER!</h2>
	<p>There are penetration testing tools included in this curriculum that must only be executed on this virtual machine and course application, or on your
        <em>own</em> projects in your <em>own</em> environment. Execution of these tools on sites you don't own can result in legal penalties.</p>
    <div class="warning">
        <h1>WARNING</h1>
        <p>Do not upload this application to a web-facing web server as it, and everything else, will be compromised.</p>
    </div>

	<h2>General Instructions</h2>
	<p>The help button allows you to view hits/tips for each vulnerability and for each security level on their respective page.</p>
</div>
