<div class=\"body_padded\">
    <h1>Security Options <img src="images/security options.png" width="40" height="40" alt=""></h1>
    <h2>Script Security</h2>
    <?php echo $this->securityLevelHtml?>
    <p>Security options include:</p>
    <ul>
        <li><b>With</b>: A file to refactor to add security.</li>
        <li><b>Without</b>: A duplicated file used as a replacement, if necessary.</li>
        <li><b>ZF</b>: An example of how Zend Framework handles a particular vulnerability.</li>
    </ul>
    <div style="margin: 10px 0 0 0;">
        <form action="index.php" method="get">
            <select name="security">
                <?php echo $this->securityOptionsHtml?>
            </select>
            <input type="hidden" name="action" value="security options">
            <input type="submit" value="Submit" name="seclev_submit">
        </form>
    </div>
</div>