<div class="body_padded">
	<h1>Vulnerability: Security Misconfiguration</h1>
	<p>(Look in the vulnerabilities folder under: <b>smc</b>)</p>
	<div class="vulnerable_code_area">
		<h2>Look at the error on the top of the screen!</h2>
		<p>This means that the display_errors configuration directive is on. </p>
		<p>Displaying errors is dangerous and likely will result in complete system takeover</p>
	</div>
</div>