<div class="body_padded">
	<h1>Vulnerability: Using Components with Known Vulnerabilities</h1>
	<p>Checking online vulnerability databases on a component you might like to use
		is a good start. However, keep in mind not all vulnerabilities are reported to
		these databases.</p>
	<p>In a case where a component is not listed in one of the below vulnerability databases,
		a code audit is required to determine the security quality of code. Does the code comply with
		standards and policies set by your organization?</p>

        <h2>For more info:</h2>
        <ul>
            <li><a href="http://cve.mitre.org">Mitre Org</a></li>
            <li><a href="http://nvd.nist.gov/home.cfm">National Vulnerability Database</a></li>
            <li><a href="http://www.securityfocus.com/vulnerabilities">Security Focus Vulnerability Search</a></li>
        </ul>
</div>